### ISSUE TITLE
Aggiungere "supporto" a go

### ISSUE THREAD

**Issue by amreo** [mapio/labprog#1]
Buongiorno profe. Può aggiornare il repository affinche tutti gli esercizi/readme.md siano "compatibili" con go?

**Comment by mapio** [comment]
Direi proprio di no :) 

La raccolta dei problemi è quanto più possibile indipendente dal linugaggio, in particolare la maggior parte dei test si basa sui flussi di input/output standard, per cui non c'è motivo di modificarli (per Go, o per qualunque altro linguaggio).

I pochi esercizi in Java (che esplicitamente richiedono la creazione di classi, o oggetti) sono molto difficilmente portabili a linguaggi diversi (certamente non in Go, che non supporta classi e oggetti).

In fine, non tengo più il corso da quest'anno, ragion per cui non svilupperò esercizi "nuovi" (magari più adatti a esercitare le parti di Go che, come per il caso delle classi di Java, sono esercitati da qualche raro esercizio in questa raccolta).

Detto questo, se qualche collega (o studente) vuole partire da questo lavoro e derivarne uno più coerente con i nuovi corsi è il benveuto (purché rispetti i termini di licenza).
